import { createCipheriv, createDecipheriv, createHash, randomBytes } from "node:crypto";
import { createAnthropic } from "@ai-sdk/anthropic";
import { createOpenAICompatible } from "@ai-sdk/openai-compatible";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { generateText, type LanguageModel } from "ai";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import type { AgentType, AiProvider, AiProviderSource } from "./ai-history.types";

type Client = SupabaseClient<Database>;
type ByokPreferences = { [key: string]: string | null; coach_ai_source: string; coach_ai_provider: string; coach_ai_model: string; coach_ai_base_url: string | null; build_ai_source: string; build_ai_provider: string; build_ai_model: string; build_ai_base_url: string | null };
type ByokSecret = { user_id: string; provider: string; encrypted_api_key: string; key_last4: string };
type ByokDatabase = Database & { public: { Tables: Database["public"]["Tables"] & { ai_preferences: { Row: Database["public"]["Tables"]["ai_preferences"]["Row"] & ByokPreferences; Insert: Database["public"]["Tables"]["ai_preferences"]["Insert"] & Partial<ByokPreferences>; Update: Database["public"]["Tables"]["ai_preferences"]["Update"] & Partial<ByokPreferences>; Relationships: [] }; ai_provider_secrets: { Row: ByokSecret; Insert: Omit<ByokSecret, "key_last4"> & { key_last4?: string }; Update: Partial<ByokSecret>; Relationships: [] } } } };
type ByokClient = SupabaseClient<ByokDatabase>;
export type AiGateway = (model: string) => LanguageModel;
export const PROVIDER_LABELS: Record<AiProvider, string> = { openai: "OpenAI", anthropic: "Anthropic", gemini: "Google Gemini", openrouter: "OpenRouter", custom: "API personnalisée" };
const DEFAULT_BASE_URLS: Record<Exclude<AiProvider, "custom" | "gemini">, string> & { gemini: string } = { openai: "https://api.openai.com/v1", anthropic: "https://api.anthropic.com/v1", gemini: "https://generativelanguage.googleapis.com/v1beta/openai", openrouter: "https://openrouter.ai/api/v1" };
const DEFAULT_MODELS: Record<Exclude<AiProvider, "custom">, string> = { openai: "gpt-5.6-luna", anthropic: "claude-sonnet-5", gemini: "gemini-3.6-flash", openrouter: "openai/gpt-5.6-luna" };
const PACE_MODEL = "gemini-3.6-flash";
const MODEL_ALLOWLISTS: Record<Exclude<AiProvider, "custom">, readonly string[]> = { openai: ["gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna", "gpt-5.1", "gpt-5", "gpt-4.1"], anthropic: ["claude-opus-5", "claude-sonnet-5", "claude-opus-4-8", "claude-opus-4-6", "claude-sonnet-4-6", "claude-haiku-4-5"], gemini: ["gemini-3.7-flash", "gemini-3.6-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite"], openrouter: ["openai/gpt-5.6-sol", "openai/gpt-5.6-luna", "anthropic/claude-sonnet-5", "anthropic/claude-opus-5", "google/gemini-3.7-flash", "deepseek/deepseek-v4-flash-0423"] };
const MODEL_LIMIT = 6;
const ALLOWED_PROVIDERS = new Set<AiProvider>(["openai", "anthropic", "gemini", "openrouter", "custom"]);
function encryptionKey() { const secret = process.env.PACE_BYOK_ENCRYPTION_KEY; if (!secret) throw new Error("BYOK non configuré côté serveur : PACE_BYOK_ENCRYPTION_KEY est manquante."); return createHash("sha256").update(secret).digest(); }
function encryptApiKey(value: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return [iv, cipher.getAuthTag(), encrypted].map((part) => part.toString("base64url")).join("."); }
function decryptApiKey(value: string) { const [iv64, tag64, data64] = value.split("."); if (!iv64 || !tag64 || !data64) throw new Error("Secret BYOK invalide."); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(iv64, "base64url")); decipher.setAuthTag(Buffer.from(tag64, "base64url")); return Buffer.concat([decipher.update(Buffer.from(data64, "base64url")), decipher.final()]).toString("utf8"); }
function validateProvider(provider: AiProvider) { if (!ALLOWED_PROVIDERS.has(provider)) throw new Error("Fournisseur IA invalide."); }
function normalizeBaseUrl(provider: AiProvider, custom?: string | null) { validateProvider(provider); const value = provider === "custom" ? custom?.trim() : DEFAULT_BASE_URLS[provider]; if (!value) throw new Error("URL API personnalisée obligatoire."); const url = new URL(value); if (url.protocol !== "https:") throw new Error("URL API invalide : HTTPS est obligatoire."); if (url.username || url.password) throw new Error("Les identifiants dans l’URL API sont interdits."); if (provider === "custom") { const hostname = url.hostname.toLowerCase(); if (hostname === "localhost" || hostname.endsWith(".localhost") || hostname.endsWith(".local") || hostname === "0.0.0.0" || hostname === "127.0.0.1" || hostname === "::1") throw new Error("URL API personnalisée non autorisée : hôte local."); if (/^10\.|^127\.|^169\.254\.|^192\.168\.|^172\.(1[6-9]|2\d|3[0-1])\./.test(hostname)) throw new Error("URL API personnalisée non autorisée : adresse réseau privée."); } return value.replace(/\/$/, ""); }
function providerModel(provider: AiProvider, apiKey: string, model: string, baseUrl?: string | null): AiGateway {
  if (provider === "gemini") { const google = createGoogleGenerativeAI({ apiKey }); return (selectedModel) => google(selectedModel || model); }
  if (provider === "anthropic") { const anthropic = createAnthropic({ apiKey, baseURL: normalizeBaseUrl("anthropic", baseUrl) }); return (selectedModel) => anthropic(selectedModel || model); }
  const headers: Record<string, string> = {}; if (provider === "openrouter") headers["X-Title"] = "Pace OS";
  const gateway = createOpenAICompatible({ name: `pace-ai-${provider}`, apiKey, baseURL: normalizeBaseUrl(provider, baseUrl), includeUsage: true, headers });
  return (selectedModel) => gateway(selectedModel || model);
}
function asByokClient(client: Client) { return client as unknown as ByokClient; }
function secretClient() { return supabaseAdmin as unknown as ByokClient; }
async function readSecret(userId: string, provider: AiProvider) { const { data, error } = await secretClient().from("ai_provider_secrets").select("encrypted_api_key,key_last4").eq("user_id", userId).eq("provider", provider).maybeSingle(); if (error) { console.error("BYOK secret lookup failed", error); throw new Error("Impossible de lire la configuration IA."); } return data; }
export function defaultModel(provider: AiProvider) { validateProvider(provider); return provider === "custom" ? "" : DEFAULT_MODELS[provider]; }
function isAllowedModel(provider: AiProvider, model: string) { if (provider === "custom") return model.trim().length > 0; return MODEL_ALLOWLISTS[provider].includes(model.trim()); }
function selectSupportedModels(provider: AiProvider, models: Array<{ id: string; name: string }>) { if (provider === "custom") return models.slice(0, MODEL_LIMIT); return MODEL_ALLOWLISTS[provider].filter((id) => models.some((model) => model.id === id)).map((id) => models.find((model) => model.id === id)!).slice(0, MODEL_LIMIT); }
async function resolveLiveModel(provider: AiProvider, key: string, baseUrl: string, requestedModel: string) { if (provider === "custom") return requestedModel; const live = await fetchProviderModels(provider, key, baseUrl); const supported = selectSupportedModels(provider, live); if (supported.length === 0) throw new Error(`Aucun modèle ${PROVIDER_LABELS[provider]} autorisé n’est actuellement disponible avec cette clé.`); if (requestedModel && supported.some((model) => model.id === requestedModel)) return requestedModel; return supported[0].id; }
export async function getAiRuntimeConfig(client: Client, userId: string, agentType: AgentType) { const byokClient = asByokClient(client); const { data, error } = await byokClient.from("ai_preferences").select("coach_ai_source,coach_ai_provider,coach_ai_model,coach_ai_base_url,build_ai_source,build_ai_provider,build_ai_model,build_ai_base_url").eq("user_id", userId).maybeSingle(); if (error) { console.error("AI preferences lookup failed", error); throw new Error("Impossible de charger la configuration IA."); } const preferences = data as ByokPreferences | null; const prefix = agentType === "coach" ? "coach_ai" : "build_ai"; const source = (preferences?.[`${prefix}_source`] ?? "pace") as AiProviderSource; const provider = (preferences?.[`${prefix}_provider`] ?? "gemini") as AiProvider; validateProvider(provider); if (source !== "pace" && source !== "byok") throw new Error("Source IA invalide."); if (source === "pace") { const key = process.env.GEMINI_API_KEY; if (!key) throw new Error("L’IA Pace n’est pas configurée sur le serveur."); return { source: "pace" as const, provider: "gemini" as AiProvider, model: PACE_MODEL, baseUrl: null, gateway: providerModel("gemini", key, PACE_MODEL), hasKey: true, keyLast4: "" }; } const model = String(preferences?.[`${prefix}_model`] ?? defaultModel(provider)).trim() || defaultModel(provider); const baseUrl = String(preferences?.[`${prefix}_base_url`] ?? ""); if (!model) throw new Error("Modèle obligatoire pour une configuration BYOK."); const normalizedBaseUrl = normalizeBaseUrl(provider, baseUrl); const secret = await readSecret(userId, provider); if (!secret?.encrypted_api_key) throw new Error(`Aucune clé ${PROVIDER_LABELS[provider]} configurée.`); const plaintext = decryptApiKey(secret.encrypted_api_key); const liveModel = await resolveLiveModel(provider, plaintext, normalizedBaseUrl, model); const gateway = providerModel(provider, plaintext, liveModel, normalizedBaseUrl); return { source, provider, model: liveModel, baseUrl: normalizedBaseUrl, gateway, hasKey: true, keyLast4: secret.key_last4 }; }
export async function saveAiProviderSettings(client: Client, userId: string, input: { agentType: AgentType; source: AiProviderSource; provider: AiProvider; model: string; baseUrl?: string | null; apiKey?: string | null }) { const byokClient = asByokClient(client); validateProvider(input.provider); if (input.source === "pace") { const patch: ByokDatabase["public"]["Tables"]["ai_preferences"]["Insert"] = input.agentType === "coach" ? { user_id: userId, coach_ai_source: "pace", coach_ai_provider: "gemini", coach_ai_model: PACE_MODEL, coach_ai_base_url: null } : { user_id: userId, build_ai_source: "pace", build_ai_provider: "gemini", build_ai_model: PACE_MODEL, build_ai_base_url: null }; const { error } = await byokClient.from("ai_preferences").upsert(patch); if (error) { console.error("AI preferences save failed", error); throw new Error("Impossible d’enregistrer la configuration IA."); } return { ok: true, source: "pace" as const, provider: "gemini" as const, model: PACE_MODEL }; } let model = input.model.trim() || defaultModel(input.provider); if (!model) throw new Error("Modèle obligatoire."); normalizeBaseUrl(input.provider, input.baseUrl); if (input.apiKey?.trim()) { const secret = input.apiKey.trim(); if (secret.length < 8) throw new Error("La clé API semble invalide."); const { error } = await secretClient().from("ai_provider_secrets").upsert({ user_id: userId, provider: input.provider, encrypted_api_key: encryptApiKey(secret), key_last4: secret.slice(-4) }, { onConflict: "user_id,provider" }); if (error) { console.error("BYOK secret save failed", error); throw new Error("Impossible d’enregistrer la clé API."); } } const existing = await readSecret(userId, input.provider); if (!existing?.encrypted_api_key) throw new Error(`Clé ${PROVIDER_LABELS[input.provider]} manquante.`); const plaintext = decryptApiKey(existing.encrypted_api_key); model = await resolveLiveModel(input.provider, plaintext, normalizeBaseUrl(input.provider, input.baseUrl), model); const patch: ByokDatabase["public"]["Tables"]["ai_preferences"]["Insert"] = input.agentType === "coach" ? { user_id: userId, coach_ai_source: "byok", coach_ai_provider: input.provider, coach_ai_model: model, coach_ai_base_url: input.provider === "custom" ? normalizeBaseUrl(input.provider, input.baseUrl) : null } : { user_id: userId, build_ai_source: "byok", build_ai_provider: input.provider, build_ai_model: model, build_ai_base_url: input.provider === "custom" ? normalizeBaseUrl(input.provider, input.baseUrl) : null }; const { error } = await byokClient.from("ai_preferences").upsert(patch); if (error) { console.error("AI preferences save failed", error); throw new Error("Impossible d’enregistrer la configuration IA."); } return { ok: true, source: "byok" as const, provider: input.provider, model }; }
export async function deleteAiProviderKey(_client: Client, userId: string, provider: AiProvider) { validateProvider(provider); const { error } = await secretClient().from("ai_provider_secrets").delete().eq("user_id", userId).eq("provider", provider); if (error) { console.error("BYOK secret deletion failed", error); throw new Error("Impossible de supprimer la clé API."); } return { ok: true }; }
export async function getAiProviderSettings(client: Client, userId: string) { const byokClient = asByokClient(client); const { data: prefs, error } = await byokClient.from("ai_preferences").select("coach_ai_source,coach_ai_provider,coach_ai_model,coach_ai_base_url,build_ai_source,build_ai_provider,build_ai_model,build_ai_base_url").eq("user_id", userId).maybeSingle(); if (error) { console.error("AI preferences read failed", error); throw new Error("Impossible de charger la configuration IA."); } const { data: secrets, error: secretError } = await secretClient().from("ai_provider_secrets").select("provider,key_last4").eq("user_id", userId); if (secretError) { console.error("BYOK secret metadata read failed", secretError); throw new Error("Impossible de charger les clés API configurées."); } const configured = new Set(secrets.map((row) => row.provider as AiProvider)); const make = (agentType: AgentType) => { const prefix = agentType === "coach" ? "coach_ai" : "build_ai"; const p = prefs as ByokPreferences | null; const source = String(p?.[`${prefix}_source`] ?? "pace") as AiProviderSource; if (source === "pace") return { source: "pace" as const, provider: "gemini" as const, model: PACE_MODEL, baseUrl: "", keyConfigured: false, keyLast4: "" }; const provider = String(p?.[`${prefix}_provider`] ?? "gemini") as AiProvider; validateProvider(provider); return { source: "byok" as const, provider, model: String(p?.[`${prefix}_model"] ?? defaultModel(provider)), baseUrl: String(p?.[`${prefix}_base_url"] ?? ""), keyConfigured: configured.has(provider), keyLast4: secrets.find((row) => row.provider === provider)?.key_last4 ?? "" }; }; return { coach: make("coach"), build: make("build"), providers: PROVIDER_LABELS }; }
function providerError(error: unknown) { const candidate = error as { status?: unknown; statusCode?: unknown; response?: { status?: unknown }; cause?: { status?: unknown; statusCode?: unknown; message?: unknown }; message?: unknown } | null; const rawStatus = candidate && typeof candidate === "object" ? candidate.status ?? candidate.statusCode ?? candidate.response?.status ?? candidate.cause?.status ?? candidate.cause?.statusCode : undefined; const status = typeof rawStatus === "number" ? rawStatus : typeof rawStatus === "string" && /^\d+$/.test(rawStatus) ? Number(rawStatus) : 0; const detailValue = candidate && typeof candidate === "object" ? candidate.cause?.message ?? candidate.message : undefined; const detail = typeof detailValue === "string" ? detailValue.replace(/^Error:\s*/i, "").trim() : ""; if (status === 400) return { status: 400, message: "Requête refusée par le fournisseur" }; if (status === 401) return { status: 401, message: "Clé API invalide" }; if (status === 403) return { status: 403, message: "Cette clé n’a pas les permissions nécessaires" }; if (status === 404) return { status: 404, message: "Modèle ou endpoint introuvable" }; if (status === 429) return { status: 429, message: "Quota ou limite de requêtes atteint chez votre fournisseur IA. Vérifiez votre quota/facturation ou sélectionnez un autre fournisseur." }; if (status >= 500) return { status, message: "Le fournisseur IA est temporairement indisponible" }; return { status: 0, message: detail ? `Connexion fournisseur impossible : ${detail}` : "Impossible de contacter le fournisseur. Vérifiez la clé, le modèle et l’URL API." }; }
export async function testAiProvider(_client: Client, userId: string, input: { provider: AiProvider; model: string; baseUrl?: string | null; apiKey?: string | null }) { validateProvider(input.provider); const stored = input.apiKey?.trim() ? null : await readSecret(userId, input.provider); const encrypted = stored?.encrypted_api_key; if (!input.apiKey?.trim() && !encrypted) return { ok: false, status: 401, message: "Clé API invalide" }; const plaintext = input.apiKey?.trim() || decryptApiKey(encrypted!); try { const model = input.model.trim() || defaultModel(input.provider); if (!model) throw new Error("Modèle obligatoire."); const gateway = providerModel(input.provider, plaintext, model, input.baseUrl); const result = await generateText({ model: gateway(model), prompt: "Réponds uniquement par OK.", maxOutputTokens: 16 }); return { ok: result.text.trim().length > 0, status: 200, message: "Connexion fournisseur OK" }; } catch (error) { console.error("AI provider connection test failed", { provider: input.provider, model: input.model, error }); return { ok: false, ...providerError(error) }; } }
async function fetchProviderModels(provider: AiProvider, key: string, baseUrl: string) { const headers: Record<string, string> = { Accept: "application/json" }; let url = `${baseUrl}/models`; if (provider === "gemini") { url = "https://generativelanguage.googleapis.com/v1beta/models"; headers["x-goog-api-key"] = key; } else if (provider === "anthropic") { headers["x-api-key"] = key; headers["anthropic-version"] = "2023-06-01"; } else { headers.Authorization = `Bearer ${key}`; } const response = await fetch(url, { headers, signal: AbortSignal.timeout(15_000) }); if (!response.ok) { const mapped = providerError({ status: response.status }); console.error("AI provider models request failed", { provider, status: response.status }); throw new Error(mapped.message); } const body = (await response.json()) as { data?: Array<{ id?: string; name?: string; display_name?: string }>; models?: Array<{ name?: string; displayName?: string; supportedGenerationMethods?: string[] }> }; if (provider === "gemini") return (body.models ?? []).filter((model) => typeof model.name === "string" && (!model.supportedGenerationMethods || model.supportedGenerationMethods.includes("generateContent"))).map((model) => ({ id: model.name!.replace(/^models\//, ""), name: model.displayName ?? model.name!.replace(/^models\//, "") })); return (body.data ?? []).filter((model) => typeof model.id === "string").map((model) => ({ id: model.id!, name: model.display_name ?? model.name ?? model.id! })); }
export async function listAiProviderModels(_client: Client, userId: string, input: { provider: AiProvider; baseUrl?: string | null; apiKey?: string | null }) { validateProvider(input.provider); const stored = input.apiKey?.trim() ? null : await readSecret(userId, input.provider); const encrypted = stored?.encrypted_api_key; if (!input.apiKey?.trim() && !encrypted) throw new Error("Clé API manquante."); const key = input.apiKey?.trim() || decryptApiKey(encrypted!); const baseUrl = normalizeBaseUrl(input.provider, input.baseUrl); const models = await fetchProviderModels(input.provider, key, baseUrl); return selectSupportedModels(input.provider, models); }
