package com.paceos.app

import android.Manifest
import android.annotation.SuppressLint
import android.content.BroadcastReceiver
import android.content.Context
import android.net.Uri
import android.content.Intent
import android.content.IntentFilter
import android.content.pm.PackageManager
import android.graphics.Color
import android.os.Build
import android.os.Bundle
import android.webkit.JavascriptInterface
import android.webkit.WebView
import android.webkit.WebViewClient
import android.webkit.ValueCallback
import android.webkit.WebChromeClient
import androidx.activity.ComponentActivity
import androidx.core.content.ContextCompat
import androidx.core.view.WindowCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.health.connect.client.HealthConnectClient
import androidx.health.connect.client.PermissionController
import androidx.lifecycle.lifecycleScope
import androidx.work.ExistingPeriodicWorkPolicy
import androidx.work.PeriodicWorkRequestBuilder
import androidx.work.WorkManager
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.launch
import org.json.JSONObject

class MainActivity : ComponentActivity() {
    private lateinit var webView: WebView
    private var filePathCallback: ValueCallback<Array<Uri>>? = null
    private val fileChooserRequestCode = 7001
    private lateinit var reader: HealthConnectReader
    private var pendingSync = false
    private val permissionLauncher = registerForActivityResult(PermissionController.createRequestPermissionResultContract()) { lifecycleScope.launch { try { val c=HealthConnectClient.getOrCreate(this@MainActivity); val g=c.permissionController.getGrantedPermissions(); if(!g.containsAll(HealthConnectReader.READ_PERMISSIONS)) sendToWeb(JSONObject().put("ok",false).put("error","Health Connect permissions are missing or were denied").put("status","permission_missing").toString()) else if(pendingSync) syncHealthConnect() } catch(_:Exception){sendToWeb(JSONObject().put("ok",false).put("error","Unable to verify Health Connect permissions").put("status","error").toString())} finally{pendingSync=false} } }
    private val blePermissionLauncher=registerForActivityResult(androidx.activity.result.contract.ActivityResultContracts.RequestMultiplePermissions()){r->val granted=r.values.all{it};sendToWatch(JSONObject().put("kind","status").put("status",JSONObject().put("status",if(granted)"bluetooth_permissions_granted" else "permission_missing").put("message",if(granted)"Bluetooth prêt" else "Les permissions Bluetooth sont nécessaires")).toString());if(granted)BleScanner.start(this)}
    private val watchReceiver=object:BroadcastReceiver(){override fun onReceive(context:Context,intent:Intent){when(intent.action){"com.paceos.app.BLE_SCAN_RESULT"->sendToWatch(JSONObject().put("kind","device").put("device",JSONObject(intent.getStringExtra("device") ?: "{}")).toString());"com.paceos.app.BLE_SCAN_STATE"->sendToWatch(JSONObject().put("kind","scan_status").put("status",JSONObject().put("status",intent.getStringExtra("status")).put("message",intent.getStringExtra("message"))).toString());"com.paceos.app.BLE_STATUS"->sendToWatch(JSONObject().put("kind","status").put("status",JSONObject().put("status",intent.getStringExtra("status")).put("message",intent.getStringExtra("message")).put("name",intent.getStringExtra("name"))).toString());"com.paceos.app.BLE_SAMPLE"->sendToWatch(JSONObject().put("kind","sample").put("sample",JSONObject(intent.getStringExtra("sample") ?: "{}")).toString())}}}
    @SuppressLint("SetJavaScriptEnabled") override fun onCreate(savedInstanceState:Bundle?){super.onCreate(savedInstanceState);configureSystemBars();reader=HealthConnectReader(this);scheduleBackgroundSync();ContextCompat.registerReceiver(this,watchReceiver,IntentFilter().apply{addAction("com.paceos.app.BLE_SCAN_RESULT");addAction("com.paceos.app.BLE_SCAN_STATE");addAction("com.paceos.app.BLE_STATUS");addAction("com.paceos.app.BLE_SAMPLE")},ContextCompat.RECEIVER_NOT_EXPORTED);webView=WebView(this).apply{settings.javaScriptEnabled=true;settings.domStorageEnabled=true;settings.allowFileAccess=false;settings.allowContentAccess=false;webViewClient=object:WebViewClient(){override fun onPageFinished(v:WebView?,url:String?){super.onPageFinished(v,url);deliverPendingQueue();deliverBleQueue()}};webChromeClient=object:WebChromeClient(){override fun onShowFileChooser(view:WebView?,callback:ValueCallback<Array<Uri>>?,params:FileChooserParams?):Boolean{filePathCallback?.onReceiveValue(null);filePathCallback=callback;return try{startActivityForResult(params?.createIntent() ?: Intent(Intent.ACTION_GET_CONTENT).apply{type="image/*";addCategory(Intent.CATEGORY_OPENABLE)},fileChooserRequestCode);true}catch(_:Exception){filePathCallback=null;false}}};addJavascriptInterface(HealthBridge(),"PaceHealthConnect");addJavascriptInterface(BleBridge(),"PaceWatch");loadUrl(BuildConfig.PACE_URL)};setContentView(webView)}
    private fun configureSystemBars(){WindowCompat.setDecorFitsSystemWindows(window,false);window.statusBarColor=Color.TRANSPARENT;window.navigationBarColor=Color.TRANSPARENT;if(Build.VERSION.SDK_INT>=29){window.isStatusBarContrastEnforced=false;window.isNavigationBarContrastEnforced=false};WindowInsetsControllerCompat(window,window.decorView).apply{isAppearanceLightStatusBars=true;isAppearanceLightNavigationBars=true}}
    @Deprecated("Use Activity Result APIs when refactoring the native shell")
    override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=fileChooserRequestCode)return;val results=if(resultCode==RESULT_OK&&data?.data!=null)arrayOf(data.data!!) else null;filePathCallback?.onReceiveValue(results);filePathCallback=null}
    override fun onDestroy(){filePathCallback?.onReceiveValue(null);filePathCallback=null;try{unregisterReceiver(watchReceiver)}catch(_:Exception){};super.onDestroy()}
    override fun onResume(){super.onResume();if(::reader.isInitialized)lifecycleScope.launch{try{if(HealthConnectClient.getSdkStatus(this@MainActivity)==HealthConnectClient.SDK_AVAILABLE){val c=HealthConnectClient.getOrCreate(this@MainActivity);if(c.permissionController.getGrantedPermissions().containsAll(HealthConnectReader.READ_PERMISSIONS))syncHealthConnect()}}catch(_:Exception){}};deliverBleQueue()}
    private fun scheduleBackgroundSync(){val r=PeriodicWorkRequestBuilder<HealthSyncWorker>(15,TimeUnit.MINUTES).build();WorkManager.getInstance(this).enqueueUniquePeriodicWork(HealthSyncWorker.UNIQUE_NAME,ExistingPeriodicWorkPolicy.UPDATE,r)}
    inner class HealthBridge{@JavascriptInterface fun requestSync(){runOnUiThread{pendingSync=true;lifecycleScope.launch{try{if(HealthConnectClient.getSdkStatus(this@MainActivity)!=HealthConnectClient.SDK_AVAILABLE){sendToWeb(JSONObject().put("ok",false).put("error","Health Connect is unavailable on this device").put("status","unavailable").toString());pendingSync=false;return@launch};val c=HealthConnectClient.getOrCreate(this@MainActivity);val g=c.permissionController.getGrantedPermissions();val required=HealthConnectReader.READ_PERMISSIONS+HealthConnectReader.BACKGROUND_READ_PERMISSION;if(!g.containsAll(required)){sendToWeb(JSONObject().put("ok",false).put("error","Health Connect permissions are required").put("status","permission_missing").toString());permissionLauncher.launch(required)}else syncHealthConnect()}catch(_:Exception){pendingSync=false;sendToWeb(JSONObject().put("ok",false).put("error","Health Connect synchronization failed").put("status","error").toString())}}}};@JavascriptInterface fun acknowledgeSync(id:String){if(id.isBlank())return;PendingHealthQueue.acknowledge(this@MainActivity,id);deliverPendingQueue()};@JavascriptInterface fun getPendingCount():Int=try{val r=PendingHealthQueue.readForDelivery(this@MainActivity);r.items.length()+r.unreadableCount}catch(_:Exception){-1}}
    inner class BleBridge{@JavascriptInterface fun requestBluetoothPermissions(){if(Build.VERSION.SDK_INT>=31)blePermissionLauncher.launch(arrayOf(Manifest.permission.BLUETOOTH_SCAN,Manifest.permission.BLUETOOTH_CONNECT)) else BleScanner.start(this@MainActivity)};@JavascriptInterface fun startScan(){if(Build.VERSION.SDK_INT>=31&&(ContextCompat.checkSelfPermission(this@MainActivity,Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED||ContextCompat.checkSelfPermission(this@MainActivity,Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED)){requestBluetoothPermissions();return};BleScanner.start(this@MainActivity)};@JavascriptInterface fun stopScan(){BleScanner.stop(this@MainActivity)};@JavascriptInterface fun connect(address:String,name:String){if(address.isBlank())return;if(Build.VERSION.SDK_INT>=31&&(ContextCompat.checkSelfPermission(this@MainActivity,Manifest.permission.BLUETOOTH_CONNECT)!=PackageManager.PERMISSION_GRANTED||ContextCompat.checkSelfPermission(this@MainActivity,Manifest.permission.BLUETOOTH_SCAN)!=PackageManager.PERMISSION_GRANTED)){requestBluetoothPermissions();return};BleSyncStore.saveDevice(this@MainActivity,address,name);val i=Intent(this@MainActivity,BleConnectionService::class.java).apply{action=BleConnectionService.ACTION_CONNECT;putExtra(BleConnectionService.EXTRA_ADDRESS,address);putExtra(BleConnectionService.EXTRA_NAME,name)};ContextCompat.startForegroundService(this@MainActivity,i)};@JavascriptInterface fun disconnect(){BleSyncStore.clearDevice(this@MainActivity);startService(Intent(this@MainActivity,BleConnectionService::class.java).setAction(BleConnectionService.ACTION_DISCONNECT))};@JavascriptInterface fun pendingCount():Int=BleSyncStore.peek(this@MainActivity).length()}
    private fun syncHealthConnect(){lifecycleScope.launch{try{val p=reader.read(7);if((p.optJSONArray("samples")?.length()?:0)>0)PendingHealthQueue.enqueue(this@MainActivity,p);deliverPendingQueue()}catch(_:Exception){sendToWeb(JSONObject().put("ok",false).put("error","Unable to read Health Connect data").put("status","read_error").toString())}finally{pendingSync=false}}}
    private fun deliverPendingQueue(){if(!::webView.isInitialized)return;try{val r=PendingHealthQueue.readForDelivery(this);if(r.unreadableCount>0)sendToWeb(JSONObject().put("ok",false).put("error",if(r.keyUnavailable)"Health Connect queue encryption key is unavailable" else "Some Health Connect queue items are unreadable").put("status",if(r.keyUnavailable)"queue_key_unavailable" else "queue_item_unreadable").put("unreadableCount",r.unreadableCount).toString());val q=r.items;for(i in 0 until q.length()){val x=q.optJSONObject(i)?:continue;sendToWeb(JSONObject().put("ok",true).put("queueId",x.optString("id")).put("payload",x.optJSONObject("payload")).put("status","queued_health_connect").toString())}}catch(_:Exception){sendToWeb(JSONObject().put("ok",false).put("error","Unable to read Health Connect queue").put("status","queue_storage_error").toString())}}
    private fun deliverBleQueue(){if(!::webView.isInitialized)return;val q=BleSyncStore.peek(this);for(i in 0 until q.length()){val x=q.optJSONObject(i)?:continue;sendToWatch(JSONObject().put("kind","sample").put("sample",x).toString())}}
    private fun sendToWatch(json:String){val q=JSONObject.quote(json);runOnUiThread{webView.evaluateJavascript("window.PaceWatch && window.PaceWatch._receive($q)",null)}}
    private fun sendToWeb(json:String){val q=JSONObject.quote(json);runOnUiThread{webView.evaluateJavascript("window.PaceHealthConnect && window.PaceHealthConnect._receive($q)",null)}}
}
