import { QueryClient } from "@tanstack/react-query";
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";
import { Route as WatchRouteImport } from "./routes/watch";

// Keep the Watch route available even when the checked-in generated route tree
// has not yet been regenerated by the Lovable/TanStack dev server.
const WatchRoute = WatchRouteImport.update({
  id: "/watch",
  path: "/watch",
  getParentRoute: () => routeTree as any,
} as any);

const runtimeRouteTree = (routeTree as any)._addFileChildren({ WatchRoute });

export const getRouter = () => {
  const queryClient = new QueryClient();

  const router = createRouter({
    routeTree: runtimeRouteTree,
    context: { queryClient },
    scrollRestoration: true,
    defaultPreloadStaleTime: 0,
  });

  return router;
};
