/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WaterRouteImport } from './routes/water'
import { Route as SportRouteImport } from './routes/sport'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecallsRouteImport } from './routes/recalls'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BodyRouteImport } from './routes/body'
import { Route as AiActivityRouteImport } from './routes/ai-activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksRemindersRouteImport } from './routes/api/public/hooks/reminders'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterRoute = WaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => rootRouteImport,
} as any)
const SportRoute = SportRouteImport.update({
  id: '/sport',
  path: '/sport',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallsRoute = RecallsRouteImport.update({
  id: '/recalls',
  path: '/recalls',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const AiActivityRoute = AiActivityRouteImport.update({
  id: '/ai-activity',
  path: '/ai-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRemindersRoute = ApiPublicHooksRemindersRouteImport.update({
  id: '/api/public/hooks/reminders',
  path: '/api/public/hooks/reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-activity': typeof AiActivityRoute
  '/body': typeof BodyRoute
  '/calendar': typeof CalendarRoute
  '/development': typeof DevelopmentRoute
  '/finance': typeof FinanceRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/recalls': typeof RecallsRoute
  '/recipes': typeof RecipesRoute
  '/routine': typeof RoutineRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/sport': typeof SportRoute
  '/water': typeof WaterRoute
  '/work': typeof WorkRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-activity': typeof AiActivityRoute
  '/body': typeof BodyRoute
  '/calendar': typeof CalendarRoute
  '/development': typeof DevelopmentRoute
  '/finance': typeof FinanceRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/recalls': typeof RecallsRoute
  '/recipes': typeof RecipesRoute
  '/routine': typeof RoutineRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/sport': typeof SportRoute
  '/water': typeof WaterRoute
  '/work': typeof WorkRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-activity': typeof AiActivityRoute
  '/body': typeof BodyRoute
  '/calendar': typeof CalendarRoute
  '/development': typeof DevelopmentRoute
  '/finance': typeof FinanceRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/nutrition': typeof NutritionRoute
  '/profile': typeof ProfileRoute
  '/recalls': typeof RecallsRoute
  '/recipes': typeof RecipesRoute
  '/routine': typeof RoutineRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/sport': typeof SportRoute
  '/water': typeof WaterRoute
  '/work': typeof WorkRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/hooks/reminders': typeof ApiPublicHooksRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-activity'
    | '/body'
    | '/calendar'
    | '/development'
    | '/finance'
    | '/investments'
    | '/login'
    | '/mcp'
    | '/nutrition'
    | '/profile'
    | '/recalls'
    | '/recipes'
    | '/routine'
    | '/scan'
    | '/settings'
    | '/sleep'
    | '/sport'
    | '/water'
    | '/work'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ai-chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-activity'
    | '/body'
    | '/calendar'
    | '/development'
    | '/finance'
    | '/investments'
    | '/login'
    | '/mcp'
    | '/nutrition'
    | '/profile'
    | '/recalls'
    | '/recipes'
    | '/routine'
    | '/scan'
    | '/settings'
    | '/sleep'
    | '/sport'
    | '/water'
    | '/work'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ai-chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/reminders'
  id:
    | '__root__'
    | '/'
    | '/ai-activity'
    | '/body'
    | '/calendar'
    | '/development'
    | '/finance'
    | '/investments'
    | '/login'
    | '/mcp'
    | '/nutrition'
    | '/profile'
    | '/recalls'
    | '/recipes'
    | '/routine'
    | '/scan'
    | '/settings'
    | '/sleep'
    | '/sport'
    | '/water'
    | '/work'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ai-chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/hooks/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiActivityRoute: typeof AiActivityRoute
  BodyRoute: typeof BodyRoute
  CalendarRoute: typeof CalendarRoute
  DevelopmentRoute: typeof DevelopmentRoute
  FinanceRoute: typeof FinanceRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  NutritionRoute: typeof NutritionRoute
  ProfileRoute: typeof ProfileRoute
  RecallsRoute: typeof RecallsRoute
  RecipesRoute: typeof RecipesRoute
  RoutineRoute: typeof RoutineRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  SportRoute: typeof SportRoute
  WaterRoute: typeof WaterRoute
  WorkRoute: typeof WorkRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHooksRemindersRoute: typeof ApiPublicHooksRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/water': {
      id: '/water'
      path: '/water'
      fullPath: '/water'
      preLoaderRoute: typeof WaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sport': {
      id: '/sport'
      path: '/sport'
      fullPath: '/sport'
      preLoaderRoute: typeof SportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recalls': {
      id: '/recalls'
      path: '/recalls'
      fullPath: '/recalls'
      preLoaderRoute: typeof RecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-activity': {
      id: '/ai-activity'
      path: '/ai-activity'
      fullPath: '/ai-activity'
      preLoaderRoute: typeof AiActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reminders': {
      id: '/api/public/hooks/reminders'
      path: '/api/public/hooks/reminders'
      fullPath: '/api/public/hooks/reminders'
      preLoaderRoute: typeof ApiPublicHooksRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiActivityRoute: AiActivityRoute,
  BodyRoute: BodyRoute,
  CalendarRoute: CalendarRoute,
  DevelopmentRoute: DevelopmentRoute,
  FinanceRoute: FinanceRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  NutritionRoute: NutritionRoute,
  ProfileRoute: ProfileRoute,
  RecallsRoute: RecallsRoute,
  RecipesRoute: RecipesRoute,
  RoutineRoute: RoutineRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  SportRoute: SportRoute,
  WaterRoute: WaterRoute,
  WorkRoute: WorkRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHooksRemindersRoute: ApiPublicHooksRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
