-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260922190317 (server_ordered_cloud_sync_and_health_realtime) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
