-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260830194105 (expand_canonical_dish_reference_catalog) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
