-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260907165808 (canonicalize_nutrition_user_state_from_food_log) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
