-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260920124418 (explicit_deny_policies_for_service_tables) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
