-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260913193605 (fix_coach_ai_food_idempotent_v2_sodium) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
