-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260919085213 (20260919120000_sport_progression_and_history_v3) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
