-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260904075508 (create_sport_backend_and_ai_tool_contract) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
