-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260923195414 (health_e2ee_pairing_revocation_hardening_v2) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
