-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260904085504 (complete_sport_rpc_contract_and_lock_provider_secrets) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
