-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260919092333 (20260919135500_reconcile_legacy_user_state_v4) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
