-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260929121445 (add_health_e2ee_foreign_key_indexes) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
