-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260903095808 (harden_food_log_ai_burst_guard_window) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
