-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260919092130 (20260919134000_safe_sport_state_sync_v5) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
