-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260922182703 (health_e2ee_device_pairing_v1_finalize) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
