-- Historical compatibility migration for Supabase Preview.
-- Remote migration version 20260902091100 (harden_reference_and_provider_secret_rls) is already recorded in Supabase.
-- Keep this no-op marker in version control so Preview can reconcile local and remote migration histories.
-- The schema change is represented by the corresponding canonical migration in this repository.
